// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/orderbook.proto

package orderbookpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBookService_GetOrderBook_FullMethodName = "/orderbook.OrderBookService/GetOrderBook"
)

// OrderBookServiceClient is the client API for OrderBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Services: functions that Arbitrage Detector can call
type OrderBookServiceClient interface {
	// Returns absolute best bid and ask for a given symbol
	GetOrderBook(ctx context.Context, in *GetTopBookRequest, opts ...grpc.CallOption) (*GetTopBookResponse, error)
}

type orderBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookServiceClient(cc grpc.ClientConnInterface) OrderBookServiceClient {
	return &orderBookServiceClient{cc}
}

func (c *orderBookServiceClient) GetOrderBook(ctx context.Context, in *GetTopBookRequest, opts ...grpc.CallOption) (*GetTopBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopBookResponse)
	err := c.cc.Invoke(ctx, OrderBookService_GetOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderBookServiceServer is the server API for OrderBookService service.
// All implementations must embed UnimplementedOrderBookServiceServer
// for forward compatibility.
//
// Services: functions that Arbitrage Detector can call
type OrderBookServiceServer interface {
	// Returns absolute best bid and ask for a given symbol
	GetOrderBook(context.Context, *GetTopBookRequest) (*GetTopBookResponse, error)
	mustEmbedUnimplementedOrderBookServiceServer()
}

// UnimplementedOrderBookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookServiceServer struct{}

func (UnimplementedOrderBookServiceServer) GetOrderBook(context.Context, *GetTopBookRequest) (*GetTopBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderBook not implemented")
}
func (UnimplementedOrderBookServiceServer) mustEmbedUnimplementedOrderBookServiceServer() {}
func (UnimplementedOrderBookServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookServiceServer will
// result in compilation errors.
type UnsafeOrderBookServiceServer interface {
	mustEmbedUnimplementedOrderBookServiceServer()
}

func RegisterOrderBookServiceServer(s grpc.ServiceRegistrar, srv OrderBookServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderBookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBookService_ServiceDesc, srv)
}

func _OrderBookService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBookService_GetOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServiceServer).GetOrderBook(ctx, req.(*GetTopBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderBookService_ServiceDesc is the grpc.ServiceDesc for OrderBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbook.OrderBookService",
	HandlerType: (*OrderBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderBook",
			Handler:    _OrderBookService_GetOrderBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/orderbook.proto",
}
