// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/orderbook.proto

package orderbookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages: exact data structures for requests and responses
// Arbitrage Detector requests from Order Book
type GetTopBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // e.g., "BTC-USD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopBookRequest) Reset() {
	*x = GetTopBookRequest{}
	mi := &file_api_proto_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopBookRequest) ProtoMessage() {}

func (x *GetTopBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopBookRequest.ProtoReflect.Descriptor instead.
func (*GetTopBookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Order Book responses to Arbitrage Detector
type GetTopBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BestBidPrice  string                 `protobuf:"bytes,2,opt,name=best_bid_price,json=bestBidPrice,proto3" json:"best_bid_price,omitempty"`
	BestBidQty    string                 `protobuf:"bytes,3,opt,name=best_bid_qty,json=bestBidQty,proto3" json:"best_bid_qty,omitempty"`
	BestAskPrice  string                 `protobuf:"bytes,4,opt,name=best_ask_price,json=bestAskPrice,proto3" json:"best_ask_price,omitempty"`
	BestAskQty    string                 `protobuf:"bytes,5,opt,name=best_ask_qty,json=bestAskQty,proto3" json:"best_ask_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopBookResponse) Reset() {
	*x = GetTopBookResponse{}
	mi := &file_api_proto_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopBookResponse) ProtoMessage() {}

func (x *GetTopBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopBookResponse.ProtoReflect.Descriptor instead.
func (*GetTopBookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTopBookResponse) GetBestBidPrice() string {
	if x != nil {
		return x.BestBidPrice
	}
	return ""
}

func (x *GetTopBookResponse) GetBestBidQty() string {
	if x != nil {
		return x.BestBidQty
	}
	return ""
}

func (x *GetTopBookResponse) GetBestAskPrice() string {
	if x != nil {
		return x.BestAskPrice
	}
	return ""
}

func (x *GetTopBookResponse) GetBestAskQty() string {
	if x != nil {
		return x.BestAskQty
	}
	return ""
}

var File_api_proto_orderbook_proto protoreflect.FileDescriptor

const file_api_proto_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/orderbook.proto\x12\torderbook\"+\n" +
	"\x11GetTopBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xbc\x01\n" +
	"\x12GetTopBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12$\n" +
	"\x0ebest_bid_price\x18\x02 \x01(\tR\fbestBidPrice\x12 \n" +
	"\fbest_bid_qty\x18\x03 \x01(\tR\n" +
	"bestBidQty\x12$\n" +
	"\x0ebest_ask_price\x18\x04 \x01(\tR\fbestAskPrice\x12 \n" +
	"\fbest_ask_qty\x18\x05 \x01(\tR\n" +
	"bestAskQty2_\n" +
	"\x10OrderBookService\x12K\n" +
	"\fGetOrderBook\x12\x1c.orderbook.GetTopBookRequest\x1a\x1d.orderbook.GetTopBookResponseB;Z9github.com/hongggweiii/market-nodes/api/proto/orderbookpbb\x06proto3"

var (
	file_api_proto_orderbook_proto_rawDescOnce sync.Once
	file_api_proto_orderbook_proto_rawDescData []byte
)

func file_api_proto_orderbook_proto_rawDescGZIP() []byte {
	file_api_proto_orderbook_proto_rawDescOnce.Do(func() {
		file_api_proto_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orderbook_proto_rawDesc), len(file_api_proto_orderbook_proto_rawDesc)))
	})
	return file_api_proto_orderbook_proto_rawDescData
}

var file_api_proto_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_orderbook_proto_goTypes = []any{
	(*GetTopBookRequest)(nil),  // 0: orderbook.GetTopBookRequest
	(*GetTopBookResponse)(nil), // 1: orderbook.GetTopBookResponse
}
var file_api_proto_orderbook_proto_depIdxs = []int32{
	0, // 0: orderbook.OrderBookService.GetOrderBook:input_type -> orderbook.GetTopBookRequest
	1, // 1: orderbook.OrderBookService.GetOrderBook:output_type -> orderbook.GetTopBookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_orderbook_proto_init() }
func file_api_proto_orderbook_proto_init() {
	if File_api_proto_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orderbook_proto_rawDesc), len(file_api_proto_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orderbook_proto_goTypes,
		DependencyIndexes: file_api_proto_orderbook_proto_depIdxs,
		MessageInfos:      file_api_proto_orderbook_proto_msgTypes,
	}.Build()
	File_api_proto_orderbook_proto = out.File
	file_api_proto_orderbook_proto_goTypes = nil
	file_api_proto_orderbook_proto_depIdxs = nil
}
